'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.18444
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace srvDataSensible
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="EventoAPP_BE", [Namespace]:="http://schemas.datacontract.org/2004/07/CGR.SEGUR.BE"),  _
     System.SerializableAttribute()>  _
    Partial Public Class EventoAPP_BE
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CAPP_CODIGOField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CEVE_CODIGOField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CEVE_DESCRIPCIONField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private NWEB_TIPO_EVENTOField As Decimal
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CAPP_CODIGO() As String
            Get
                Return Me.CAPP_CODIGOField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CAPP_CODIGOField, value) <> true) Then
                    Me.CAPP_CODIGOField = value
                    Me.RaisePropertyChanged("CAPP_CODIGO")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CEVE_CODIGO() As String
            Get
                Return Me.CEVE_CODIGOField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CEVE_CODIGOField, value) <> true) Then
                    Me.CEVE_CODIGOField = value
                    Me.RaisePropertyChanged("CEVE_CODIGO")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CEVE_DESCRIPCION() As String
            Get
                Return Me.CEVE_DESCRIPCIONField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CEVE_DESCRIPCIONField, value) <> true) Then
                    Me.CEVE_DESCRIPCIONField = value
                    Me.RaisePropertyChanged("CEVE_DESCRIPCION")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property NWEB_TIPO_EVENTO() As Decimal
            Get
                Return Me.NWEB_TIPO_EVENTOField
            End Get
            Set
                If (Me.NWEB_TIPO_EVENTOField.Equals(value) <> true) Then
                    Me.NWEB_TIPO_EVENTOField = value
                    Me.RaisePropertyChanged("NWEB_TIPO_EVENTO")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="AuditoriaBE", [Namespace]:="http://schemas.datacontract.org/2004/07/CGR.SEGUR.BE"),  _
     System.SerializableAttribute()>  _
    Partial Public Class AuditoriaBE
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CAPP_CODIGOField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CAUDI_EST_EXITOField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CEVE_CODIGOField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CWEB_EXCEPCIONField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CWEB_IPField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CWEB_MENSAJEField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CWEB_REQUEST_URLField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CWEB_USUARIO_ACCEDIDOField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CWEB_USUARIO_CODIGOField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CWEB_VALORESField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private NWEB_CODIGOField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private NWEB_TIPO_EVENTOField As Integer
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CAPP_CODIGO() As String
            Get
                Return Me.CAPP_CODIGOField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CAPP_CODIGOField, value) <> true) Then
                    Me.CAPP_CODIGOField = value
                    Me.RaisePropertyChanged("CAPP_CODIGO")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CAUDI_EST_EXITO() As String
            Get
                Return Me.CAUDI_EST_EXITOField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CAUDI_EST_EXITOField, value) <> true) Then
                    Me.CAUDI_EST_EXITOField = value
                    Me.RaisePropertyChanged("CAUDI_EST_EXITO")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CEVE_CODIGO() As String
            Get
                Return Me.CEVE_CODIGOField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CEVE_CODIGOField, value) <> true) Then
                    Me.CEVE_CODIGOField = value
                    Me.RaisePropertyChanged("CEVE_CODIGO")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CWEB_EXCEPCION() As String
            Get
                Return Me.CWEB_EXCEPCIONField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CWEB_EXCEPCIONField, value) <> true) Then
                    Me.CWEB_EXCEPCIONField = value
                    Me.RaisePropertyChanged("CWEB_EXCEPCION")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CWEB_IP() As String
            Get
                Return Me.CWEB_IPField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CWEB_IPField, value) <> true) Then
                    Me.CWEB_IPField = value
                    Me.RaisePropertyChanged("CWEB_IP")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CWEB_MENSAJE() As String
            Get
                Return Me.CWEB_MENSAJEField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CWEB_MENSAJEField, value) <> true) Then
                    Me.CWEB_MENSAJEField = value
                    Me.RaisePropertyChanged("CWEB_MENSAJE")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CWEB_REQUEST_URL() As String
            Get
                Return Me.CWEB_REQUEST_URLField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CWEB_REQUEST_URLField, value) <> true) Then
                    Me.CWEB_REQUEST_URLField = value
                    Me.RaisePropertyChanged("CWEB_REQUEST_URL")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CWEB_USUARIO_ACCEDIDO() As String
            Get
                Return Me.CWEB_USUARIO_ACCEDIDOField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CWEB_USUARIO_ACCEDIDOField, value) <> true) Then
                    Me.CWEB_USUARIO_ACCEDIDOField = value
                    Me.RaisePropertyChanged("CWEB_USUARIO_ACCEDIDO")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CWEB_USUARIO_CODIGO() As String
            Get
                Return Me.CWEB_USUARIO_CODIGOField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CWEB_USUARIO_CODIGOField, value) <> true) Then
                    Me.CWEB_USUARIO_CODIGOField = value
                    Me.RaisePropertyChanged("CWEB_USUARIO_CODIGO")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CWEB_VALORES() As String
            Get
                Return Me.CWEB_VALORESField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CWEB_VALORESField, value) <> true) Then
                    Me.CWEB_VALORESField = value
                    Me.RaisePropertyChanged("CWEB_VALORES")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property NWEB_CODIGO() As Integer
            Get
                Return Me.NWEB_CODIGOField
            End Get
            Set
                If (Me.NWEB_CODIGOField.Equals(value) <> true) Then
                    Me.NWEB_CODIGOField = value
                    Me.RaisePropertyChanged("NWEB_CODIGO")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property NWEB_TIPO_EVENTO() As Integer
            Get
                Return Me.NWEB_TIPO_EVENTOField
            End Get
            Set
                If (Me.NWEB_TIPO_EVENTOField.Equals(value) <> true) Then
                    Me.NWEB_TIPO_EVENTOField = value
                    Me.RaisePropertyChanged("NWEB_TIPO_EVENTO")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="RespuestaBE", [Namespace]:="http://schemas.datacontract.org/2004/07/CGR.SEGUR.BE"),  _
     System.SerializableAttribute()>  _
    Partial Public Class RespuestaBE
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ListaRetornoField As System.Collections.Generic.List(Of srvDataSensible.GenericoBE)
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private MensajeField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private RespuestaField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ValorRertonoField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ListaRetorno() As System.Collections.Generic.List(Of srvDataSensible.GenericoBE)
            Get
                Return Me.ListaRetornoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ListaRetornoField, value) <> true) Then
                    Me.ListaRetornoField = value
                    Me.RaisePropertyChanged("ListaRetorno")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Mensaje() As String
            Get
                Return Me.MensajeField
            End Get
            Set
                If (Object.ReferenceEquals(Me.MensajeField, value) <> true) Then
                    Me.MensajeField = value
                    Me.RaisePropertyChanged("Mensaje")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Respuesta() As Boolean
            Get
                Return Me.RespuestaField
            End Get
            Set
                If (Me.RespuestaField.Equals(value) <> true) Then
                    Me.RespuestaField = value
                    Me.RaisePropertyChanged("Respuesta")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ValorRertono() As String
            Get
                Return Me.ValorRertonoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ValorRertonoField, value) <> true) Then
                    Me.ValorRertonoField = value
                    Me.RaisePropertyChanged("ValorRertono")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="GenericoBE", [Namespace]:="http://schemas.datacontract.org/2004/07/CGR.SEGUR.BE"),  _
     System.SerializableAttribute()>  _
    Partial Public Class GenericoBE
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DatoField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Dato() As String
            Get
                Return Me.DatoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DatoField, value) <> true) Then
                    Me.DatoField = value
                    Me.RaisePropertyChanged("Dato")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="EventoBE", [Namespace]:="http://schemas.datacontract.org/2004/07/CGR.SEGUR.BE"),  _
     System.SerializableAttribute()>  _
    Partial Public Class EventoBE
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CAPP_CODIGOField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CWEB_EXCEPCIONField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CWEB_IPField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CWEB_MENSAJEField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CWEB_REQUEST_URLField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CWEB_USUARIO_CODIGOField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CWEB_VALORESField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private NWEB_CODIGOField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private NWEB_TIPO_EVENTOField As Integer
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CAPP_CODIGO() As String
            Get
                Return Me.CAPP_CODIGOField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CAPP_CODIGOField, value) <> true) Then
                    Me.CAPP_CODIGOField = value
                    Me.RaisePropertyChanged("CAPP_CODIGO")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CWEB_EXCEPCION() As String
            Get
                Return Me.CWEB_EXCEPCIONField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CWEB_EXCEPCIONField, value) <> true) Then
                    Me.CWEB_EXCEPCIONField = value
                    Me.RaisePropertyChanged("CWEB_EXCEPCION")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CWEB_IP() As String
            Get
                Return Me.CWEB_IPField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CWEB_IPField, value) <> true) Then
                    Me.CWEB_IPField = value
                    Me.RaisePropertyChanged("CWEB_IP")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CWEB_MENSAJE() As String
            Get
                Return Me.CWEB_MENSAJEField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CWEB_MENSAJEField, value) <> true) Then
                    Me.CWEB_MENSAJEField = value
                    Me.RaisePropertyChanged("CWEB_MENSAJE")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CWEB_REQUEST_URL() As String
            Get
                Return Me.CWEB_REQUEST_URLField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CWEB_REQUEST_URLField, value) <> true) Then
                    Me.CWEB_REQUEST_URLField = value
                    Me.RaisePropertyChanged("CWEB_REQUEST_URL")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CWEB_USUARIO_CODIGO() As String
            Get
                Return Me.CWEB_USUARIO_CODIGOField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CWEB_USUARIO_CODIGOField, value) <> true) Then
                    Me.CWEB_USUARIO_CODIGOField = value
                    Me.RaisePropertyChanged("CWEB_USUARIO_CODIGO")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CWEB_VALORES() As String
            Get
                Return Me.CWEB_VALORESField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CWEB_VALORESField, value) <> true) Then
                    Me.CWEB_VALORESField = value
                    Me.RaisePropertyChanged("CWEB_VALORES")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property NWEB_CODIGO() As Integer
            Get
                Return Me.NWEB_CODIGOField
            End Get
            Set
                If (Me.NWEB_CODIGOField.Equals(value) <> true) Then
                    Me.NWEB_CODIGOField = value
                    Me.RaisePropertyChanged("NWEB_CODIGO")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property NWEB_TIPO_EVENTO() As Integer
            Get
                Return Me.NWEB_TIPO_EVENTOField
            End Get
            Set
                If (Me.NWEB_TIPO_EVENTOField.Equals(value) <> true) Then
                    Me.NWEB_TIPO_EVENTOField = value
                    Me.RaisePropertyChanged("NWEB_TIPO_EVENTO")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="srvDataSensible.IAuditoria")>  _
    Public Interface IAuditoria
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IAuditoria/EventosAplicacionListar", ReplyAction:="http://tempuri.org/IAuditoria/EventosAplicacionListarResponse")>  _
        Function EventosAplicacionListar(ByVal codigoSistema As String) As System.Collections.Generic.List(Of srvDataSensible.EventoAPP_BE)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IAuditoria/GuardarAuditoria", ReplyAction:="http://tempuri.org/IAuditoria/GuardarAuditoriaResponse")>  _
        Function GuardarAuditoria(ByVal objEventoBE As srvDataSensible.AuditoriaBE) As srvDataSensible.RespuestaBE
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IAuditoria/GuardarEvento", ReplyAction:="http://tempuri.org/IAuditoria/GuardarEventoResponse")>  _
        Function GuardarEvento(ByRef objDato As srvDataSensible.EventoBE) As srvDataSensible.RespuestaBE
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface IAuditoriaChannel
        Inherits srvDataSensible.IAuditoria, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class AuditoriaClient
        Inherits System.ServiceModel.ClientBase(Of srvDataSensible.IAuditoria)
        Implements srvDataSensible.IAuditoria
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function EventosAplicacionListar(ByVal codigoSistema As String) As System.Collections.Generic.List(Of srvDataSensible.EventoAPP_BE) Implements srvDataSensible.IAuditoria.EventosAplicacionListar
            Return MyBase.Channel.EventosAplicacionListar(codigoSistema)
        End Function
        
        Public Function GuardarAuditoria(ByVal objEventoBE As srvDataSensible.AuditoriaBE) As srvDataSensible.RespuestaBE Implements srvDataSensible.IAuditoria.GuardarAuditoria
            Return MyBase.Channel.GuardarAuditoria(objEventoBE)
        End Function
        
        Public Function GuardarEvento(ByRef objDato As srvDataSensible.EventoBE) As srvDataSensible.RespuestaBE Implements srvDataSensible.IAuditoria.GuardarEvento
            Return MyBase.Channel.GuardarEvento(objDato)
        End Function
    End Class
End Namespace
